<a href="https://colab.research.google.com/github/jyotishsanchi/NLP_Learnings/blob/main/WordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Word Embedding Techniques using Embedding Layer in Keras

In [29]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [30]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [31]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [32]:
### Vocabulary size
voc_size=10000

### One Hot Representation

In [33]:
onehot_repr = []
for words in sent:
  onehot_repr.append(one_hot(words, voc_size))

print(onehot_repr)  

[[8629, 6839, 331, 4988], [8629, 6839, 331, 7234], [8629, 7241, 331, 2066], [4417, 5105, 1920, 4281, 4073], [4417, 5105, 1920, 4281, 4503], [1806, 8629, 422, 331, 9164], [238, 1568, 9370, 4281]]


In [34]:
# onehot_reprr=[one_hot(words,voc_size)for words in sent] 
# print(onehot_reprr)

### Word Embedding Represntation

In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [36]:
import numpy as np

### Pad sequences to ensure all are of same length

In [37]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8629 6839  331 4988]
 [   0    0    0    0 8629 6839  331 7234]
 [   0    0    0    0 8629 7241  331 2066]
 [   0    0    0 4417 5105 1920 4281 4073]
 [   0    0    0 4417 5105 1920 4281 4503]
 [   0    0    0 1806 8629  422  331 9164]
 [   0    0    0    0  238 1568 9370 4281]]


### Set dimention to convert index to feature representation

In [38]:
dim=10

In [39]:

model=Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [41]:
print(model.predict(embedded_docs))

[[[ 3.59052457e-02  4.22894023e-02 -4.47546616e-02 -4.41272967e-02
   -4.04561758e-02 -1.04329959e-02 -3.69308144e-03 -3.31836939e-02
   -1.67893656e-02  3.41646411e-02]
  [ 3.59052457e-02  4.22894023e-02 -4.47546616e-02 -4.41272967e-02
   -4.04561758e-02 -1.04329959e-02 -3.69308144e-03 -3.31836939e-02
   -1.67893656e-02  3.41646411e-02]
  [ 3.59052457e-02  4.22894023e-02 -4.47546616e-02 -4.41272967e-02
   -4.04561758e-02 -1.04329959e-02 -3.69308144e-03 -3.31836939e-02
   -1.67893656e-02  3.41646411e-02]
  [ 3.59052457e-02  4.22894023e-02 -4.47546616e-02 -4.41272967e-02
   -4.04561758e-02 -1.04329959e-02 -3.69308144e-03 -3.31836939e-02
   -1.67893656e-02  3.41646411e-02]
  [-1.23502612e-02 -1.51433572e-02 -3.13978679e-02 -3.52885239e-02
   -9.57237557e-03  1.96409225e-03  3.29161920e-02  1.83028243e-02
   -4.07078154e-02  3.34009193e-02]
  [-2.91560534e-02  3.40231173e-02  3.12939771e-02 -1.17474422e-02
   -1.64365061e-02 -3.41168530e-02  1.89705007e-02 -1.91026926e-03
    4.01954912e-

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0, 8629, 6839,  331, 4988], dtype=int32)

In [43]:
print(model.predict(embedded_docs)[0])

[[ 3.5905246e-02  4.2289402e-02 -4.4754662e-02 -4.4127297e-02
  -4.0456176e-02 -1.0432996e-02 -3.6930814e-03 -3.3183694e-02
  -1.6789366e-02  3.4164641e-02]
 [ 3.5905246e-02  4.2289402e-02 -4.4754662e-02 -4.4127297e-02
  -4.0456176e-02 -1.0432996e-02 -3.6930814e-03 -3.3183694e-02
  -1.6789366e-02  3.4164641e-02]
 [ 3.5905246e-02  4.2289402e-02 -4.4754662e-02 -4.4127297e-02
  -4.0456176e-02 -1.0432996e-02 -3.6930814e-03 -3.3183694e-02
  -1.6789366e-02  3.4164641e-02]
 [ 3.5905246e-02  4.2289402e-02 -4.4754662e-02 -4.4127297e-02
  -4.0456176e-02 -1.0432996e-02 -3.6930814e-03 -3.3183694e-02
  -1.6789366e-02  3.4164641e-02]
 [-1.2350261e-02 -1.5143357e-02 -3.1397868e-02 -3.5288524e-02
  -9.5723756e-03  1.9640923e-03  3.2916192e-02  1.8302824e-02
  -4.0707815e-02  3.3400919e-02]
 [-2.9156053e-02  3.4023117e-02  3.1293977e-02 -1.1747442e-02
  -1.6436506e-02 -3.4116853e-02  1.8970501e-02 -1.9102693e-03
   4.0195491e-02 -2.8274490e-02]
 [-4.4208016e-02  4.8190463e-02 -2.3983467e-02 -1.9922972e